package: jblock
version: '1.0.0-beta-1'
name: JBlock
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/JBlock

page:
    title: 'translate:title'
    pjax: true
    perm: jblock[]
    subpages:
        overview: { title: 'translate:overview' }
        demo:
            title: 'translate:demo_base'

requires:
    redaxo: '^5.1.0'