package: mblock
version: '1.3.1'
name: MBlock
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mblock

page:
    title: 'translate:title'
    pjax: true
    perm: mblock[]
    subpages:
        overview: { title: 'translate:overview' }
        demo:
            title: 'translate:demo_base'

requires:
    redaxo: '^5.1.0'
